#!/usr/bin/env python

import time
from sbigclient.sbigcam import F9WFSCam


cam = F9WFSCam()

cam.process_events()
cam.process_events()
cam.process_events()

cam.cooling_on()
cam.temperature = -15.0

time.sleep(2)
cam.process_events()
cam.process_events()

cam.quit()
