#!/usr/bin/env python

import time
from indiclient.indicam import F9WFSCam


cam = F9WFSCam()

cam.process_events()
cam.process_events()
cam.process_events()

cam.cooling_off()
cam.temperature = 10.0

time.sleep(2)
cam.quit()
