#!/usr/bin/env python

import time
from indiclient.indicam import F9WFSCam


cam = F9WFSCam()

cam.process_events()
cam.process_events()
cam.process_events()

cam.default_config()

time.sleep(2)
cam.process_events()
cam.process_events()
cam.process_events()

cam.quit()
