# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: Python Tests

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  schedule:
    # run every Monday at 6am UTC
    - cron: '0 6 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV }}
    with:
      submodules: false
      coverage: ''
      envs: |
        - name: Codestyle
          linux: codestyle

        - name: Python 3.12 on Linux with all dependencies, remote data, and coverage
          linux: py312-test-cov
          coverage: codecov
          toxargs: -v
          posargs: --remote-data=any

        - name: (Allowed Failure) Python 3.12 on Linux with dev dependencies
          linux: py312-test-astropydev
          toxargs: -v
